# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ****Data Import****

In [2]:
raw_data=pd.read_csv('/content/sample_data/dirty_cafe_sales.csv')

df=raw_data.copy()

df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

# ****Initial Inspection****

In [8]:
def summ_and_report():

  print("Number of rows:", df.shape[0])
  print("Number of columns:", df.shape[1])

  print("\nNumber of duplicates")
  print(df.duplicated().sum())

  print("\nInfo:")
  print(df.info())

  print("\nStatistical summary:")
  print(df.describe())

  print("\nNumber of missing values")
  print(df.isna().sum())

summ_and_report()

Number of rows: 10000
Number of columns: 8

Number of duplicates
0

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB
None

Statistical summary:
       Transaction ID   Item Quantity Price Per Unit Total Spent  \
count           10000   9667     9862           9821        9827
unique          10000     10        7              8          19
top       TXN_9226047  Juice        5            3.0         6.0
freq                1   1171     2013           2429         979

        Payment Method  Location Transaction Date
count             7421      6735             9841
unique               5         4              367
top     Digital Wallet  Takeaway          UNKNOWN
freq              2291      3022              159

Number of missing values
Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

# Unique values in each column

In [11]:
for i in df.columns:
  print("\n","--"*80 ,"\n")
  display(df[i].unique())

 ----------------------------------------------------------------------------------------------------------------------------------------------------------------

array(['TXN_1961373', 'TXN_4977031', 'TXN_4271903', ..., 'TXN_5255387',
       'TXN_7695629', 'TXN_6170729'], dtype=object)

 ----------------------------------------------------------------------------------------------------------------------------------------------------------------

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'UNKNOWN',
       'Sandwich', nan, 'ERROR', 'Juice', 'Tea'], dtype=object)

 ----------------------------------------------------------------------------------------------------------------------------------------------------------------

array(['2', '4', '5', '3', '1', 'ERROR', 'UNKNOWN', nan], dtype=object)

 ----------------------------------------------------------------------------------------------------------------------------------------------------------------

array(['2.0', '3.0', '1.0', '5.0', '4.0', '1.5', nan, 'ERROR', 'UNKNOWN'],
      dtype=object)

 ----------------------------------------------------------------------------------------------------------------------------------------------------------------

array(['4.0', '12.0', 'ERROR', '10.0', '20.0', '9.0', '16.0', '15.0',
       '25.0', '8.0', '5.0', '3.0', '6.0', nan, 'UNKNOWN', '2.0', '1.0',
       '7.5', '4.5', '1.5'], dtype=object)

 ----------------------------------------------------------------------------------------------------------------------------------------------------------------

array(['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR', nan],
      dtype=object)

 ----------------------------------------------------------------------------------------------------------------------------------------------------------------

array(['Takeaway', 'In-store', 'UNKNOWN', nan, 'ERROR'], dtype=object)

 ----------------------------------------------------------------------------------------------------------------------------------------------------------------

array(['2023-09-08', '2023-05-16', '2023-07-19', '2023-04-27',
       '2023-06-11', '2023-03-31', '2023-10-06', '2023-10-28',
       '2023-07-28', '2023-12-31', '2023-11-07', 'ERROR', '2023-05-03',
       '2023-06-01', '2023-03-21', '2023-11-15', '2023-06-10',
       '2023-02-24', '2023-03-25', '2023-01-15', '2023-04-04',
       '2023-03-30', '2023-12-01', '2023-09-18', '2023-06-03',
       '2023-12-13', '2023-04-20', '2023-04-10', '2023-03-11',
       '2023-06-02', '2023-11-06', '2023-08-15', '2023-10-09',
       '2023-05-28', '2023-07-17', '2023-04-29', '2023-06-08',
       '2023-06-29', '2023-04-17', '2023-12-22', '2023-01-10',
       '2023-10-02', '2023-02-23', '2023-03-22', '2023-11-03',
       '2023-03-02', '2023-06-26', '2023-05-02', '2023-09-05',
       '2023-01-08', '2023-03-15', '2023-11-25', '2023-12-05',
       '2023-03-19', '2023-06-27', '2023-04-19', '2023-10-07',
       '2023-09-30', '2023-05-27', '2023-11-18', '2023-10-20',
       '2023-10-03', '2023-10-27', '2023-04-06', '2023-01-31',
       '2023-12-08', '2023-06-19', '2023-12-14', '2023-07-16',
       '2023-02-22', nan, '2023-06-15', '2023-12-09', '2023-04-18',
       '2023-10-29', '2023-04-30', '2023-04-02', '2023-05-24',
       '2023-03-12', '2023-08-16', '2023-09-10', '2023-03-07',
       '2023-08-07', '2023-08-20', '2023-04-15', '2023-07-25',
       '2023-10-30', '2023-12-15', '2023-02-25', '2023-04-03',
       '2023-10-08', '2023-12-28', '2023-08-30', '2023-02-03',
       '2023-09-12', '2023-05-04', '2023-02-21', 'UNKNOWN', '2023-03-16',
       '2023-02-06', '2023-03-29', '2023-06-18', '2023-09-23',
       '2023-01-14', '2023-09-14', '2023-09-16', '2023-04-08',
       '2023-12-19', '2023-07-14', '2023-12-12', '2023-01-05',
       '2023-01-23', '2023-02-20', '2023-12-06', '2023-05-31',
       '2023-08-11', '2023-09-03', '2023-07-11', '2023-06-06',
       '2023-01-18', '2023-03-23', '2023-01-04', '2023-06-23',
       '2023-08-03', '2023-07-12', '2023-11-02', '2023-07-31',
       '2023-09-19', '2023-02-09', '2023-09-04', '2023-05-21',
       '2023-07-02', '2023-07-10', '2023-11-21', '2023-12-02',
       '2023-03-13', '2023-08-12', '2023-02-16', '2023-04-11',
       '2023-03-26', '2023-11-01', '2023-07-22', '2023-07-26',
       '2023-02-28', '2023-01-27', '2023-01-19', '2023-04-07',
       '2023-03-20', '2023-12-27', '2023-10-26', '2023-02-18',
       '2023-05-15', '2023-12-10', '2023-04-21', '2023-02-04',
       '2023-11-12', '2023-08-05', '2023-05-10', '2023-07-15',
       '2023-01-11', '2023-10-01', '2023-04-26', '2023-08-25',
       '2023-03-01', '2023-11-13', '2023-07-09', '2023-05-13',
       '2023-05-18', '2023-01-17', '2023-09-22', '2023-08-22',
       '2023-07-27', '2023-12-30', '2023-12-21', '2023-09-28',
       '2023-11-16', '2023-04-14', '2023-01-03', '2023-01-12',
       '2023-08-31', '2023-07-07', '2023-09-15', '2023-10-21',
       '2023-09-02', '2023-08-19', '2023-01-06', '2023-10-13',
       '2023-05-29', '2023-05-22', '2023-11-23', '2023-10-15',
       '2023-11-14', '2023-11-26', '2023-12-17', '2023-05-09',
       '2023-10-22', '2023-06-30', '2023-04-25', '2023-02-19',
       '2023-12-11', '2023-10-12', '2023-07-04', '2023-01-28',
       '2023-10-04', '2023-02-26', '2023-10-11', '2023-02-14',
       '2023-04-28', '2023-09-06', '2023-04-23', '2023-01-22',
       '2023-03-10', '2023-01-09', '2023-12-03', '2023-08-06',
       '2023-12-29', '2023-02-15', '2023-05-25', '2023-10-31',
       '2023-02-27', '2023-03-03', '2023-09-27', '2023-08-18',
       '2023-12-16', '2023-06-07', '2023-05-12', '2023-07-06',
       '2023-06-20', '2023-08-09', '2023-05-14', '2023-07-18',
       '2023-10-10', '2023-02-02', '2023-08-14', '2023-09-26',
       '2023-01-13', '2023-10-16', '2023-11-17', '2023-12-20',
       '2023-12-04', '2023-02-08', '2023-09-11', '2023-02-01',
       '2023-02-12', '2023-03-14', '2023-09-29', '2023-04-22',
       '2023-06-13', '2023-12-24', '2023-03-28', '2023-03-06',
       '2023-02-11', '2023-01-30', '2023-04-09', '2023-04-16',
       '2023-12-23', '2023-03-05', '2023-03-24', '2023-07-23',
       '2023-07-29', '2023-06-05', '2023-10-19', '2023-01-07',
       '2023-11-29', '2023-07-05', '2023-07-20', '2023-05-07',
       '2023-08-10', '2023-10-24', '2023-08-13', '2023-08-28',
       '2023-06-21', '2023-11-10', '2023-10-18', '2023-05-19',
       '2023-11-09', '2023-06-24', '2023-05-11', '2023-12-07',
       '2023-09-01', '2023-09-25', '2023-06-22', '2023-05-30',
       '2023-04-24', '2023-09-20', '2023-02-07', '2023-05-05',
       '2023-02-10', '2023-11-24', '2023-10-25', '2023-10-05',
       '2023-07-21', '2023-07-08', '2023-03-17', '2023-10-14',
       '2023-06-28', '2023-09-09', '2023-08-21', '2023-07-01',
       '2023-06-14', '2023-03-09', '2023-11-08', '2023-12-26',
       '2023-09-13', '2023-05-23', '2023-08-24', '2023-04-01',
       '2023-06-09', '2023-08-23', '2023-08-08', '2023-08-27',
       '2023-05-26', '2023-06-16', '2023-12-25', '2023-01-25',
       '2023-10-23', '2023-05-06', '2023-01-29', '2023-08-29',
       '2023-01-01', '2023-07-24', '2023-04-12', '2023-12-18',
       '2023-09-21', '2023-05-01', '2023-02-05', '2023-01-24',
       '2023-01-02', '2023-06-12', '2023-01-16', '2023-10-17',
       '2023-03-04', '2023-06-17', '2023-03-18', '2023-08-26',
       '2023-05-17', '2023-11-22', '2023-08-17', '2023-11-19',
       '2023-11-27', '2023-06-04', '2023-09-17', '2023-11-04',
       '2023-11-28', '2023-06-25', '2023-04-13', '2023-01-26',
       '2023-08-04', '2023-05-08', '2023-11-20', '2023-07-13',
       '2023-09-24', '2023-01-21', '2023-03-08', '2023-09-07',
       '2023-11-30', '2023-08-02', '2023-04-05', '2023-08-01',
       '2023-01-20', '2023-11-11', '2023-02-13', '2023-07-30',
       '2023-02-17', '2023-05-20', '2023-11-05', '2023-03-27',
       '2023-07-03'], dtype=object)

## ****What Changes need to make ?****  
1. **But first we need to replace 'Unknown', 'ERROR' with np.nan to show it as null values.**
2. **Assign Right Datatype to the columns.**
3. **Then We need to Calculate null values in `Quantity`, `Price Per Unit`, `Total Spent`.**
4. **For columns like `Payment Method`, `Location` missing values are missing completely at random and**
    **these column does not form any relation with others so we can fill missing values in these column using random sample method.**
5. **For `Transaction Date` Column we can calculate missig using interpolate method.**

## ****Replace 'ERROR', 'UNKNOWN' values in data as `Null`****

In [12]:
df.replace(['ERROR', 'UNKNOWN'], np.nan, inplace = True)

df[['Quantity', 'Price Per Unit', 'Total Spent']] = df[['Quantity', 'Price Per Unit', 'Total Spent']].astype(np.float64)

df['Transaction Date'] = pd.to_datetime(df['Transaction Date'])

## ****Calculate null values in `Quantity`, `Price Per Unit`, `Total Spent`****

- We can use formula **`Total Spent`** = **`Quantity`** * **`Price Per Unit`** to calculate missing values all three columns.

In [13]:
def null_calculator(df):

    df['Quantity'] = df['Quantity'].fillna(df['Total Spent'] / df['Price Per Unit'])

    df['Price Per Unit'] = df['Price Per Unit'].fillna(df['Total Spent'] / df['Quantity'])

    df['Total Spent'] = df['Total Spent'].fillna(df['Quantity'] * df['Price Per Unit'])

null_calculator(df)

## ****Calculate Null in `Item` Column****

- In this column we can calculate missing data using Price Per Item.
- But there is catche that `Sandwitch` and `Smoothie` has same price so we have to randomly sample these priced values.
- Another values like `Cake` and `Juice` has same Price and we will calculate these by same method.

In [14]:
def item_missing_cal(df):

    # Creating Price map
    price_map = {2.0 : 'Coffee', 1.50 : 'Tea', 5.0 : 'Salad', 1.0 : 'Cookie'}

    # Create replacement using map
    replace = df['Price Per Unit'].map(price_map)

    # Calculate missing using replacement
    df['Item'] = df['Item'].fillna(replace)

item_missing_cal(df)

In [15]:
# For Items at price == 3.0

def missing_item_price_3(df):

    # Item are at price == 3.0
    maping = ['Cake', 'Juice']

    # Find rows that meet criteria
    masking = ((df['Item'].isnull()) & (df['Price Per Unit'] == 3))

    # Value Count of missing
    count = masking.sum()

    # Calculate missing
    if count > 0:
        df.loc[masking, 'Item'] = np.random.choice(maping, size = count, p = [0.5, 0.5])                   # Here p = [0.5, 0.5] means it will fill 50%-50% both values.


missing_item_price_3(df)

In [16]:
# For Items at Price == 4.0

def missing_item_price_4(df):

    # Items at price 4
    items = ['Sandwich', 'Smoothie']

    # Find rows that meet criteria
    rows = ((df['Item'].isnull()) & (df['Price Per Unit'] == 4.0))

    # Count of these rows
    counts = rows.sum()

    # Calculate missing
    if counts > 0:
        df.loc[rows, 'Item'] = np.random.choice(items, size = counts, p = [0.5, 0.5])


missing_item_price_4(df)

## ****Calculate missing in Payment method and location****

In [18]:
mask = df['Payment Method'].isnull()

df.loc[mask, 'Payment Method'] = (
    df['Payment Method']
    .dropna()
    .sample(mask.sum())
    .values
)

df['Location'][df['Location'].isnull()] = df['Location'].dropna().sample(df['Location'].isnull().sum()).values

mask = df['Location'].isnull()

df.loc[mask, 'Location'] = (
    df['Location']
    .dropna()
    .sample(mask.sum())
    .values
)

/tmp/ipykernel_165/3414590212.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['Location'][df['Location'].isnull()] = df['Location'].dropna().sample(df['Location'].isnull().sum()).values
/tmp/ipykernel_165/3414590212.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Location'][df['Location'].isnull()] = df['Location'].dropna().sample(df['Location'].isnull().sum()).values

## ****Calculate null in Transaction Date column****

In [19]:
numeric_date = df['Transaction Date'].view('int64')

numeric_date = numeric_date.where(df['Transaction Date'].notna(), np.nan)

df['Transaction Date'] = pd.to_datetime(numeric_date.interpolate(method = 'linear'))

#df['Transaction Date']

/tmp/ipykernel_165/2252086455.py:1: FutureWarning: Series.view is deprecated and will be removed in a future version. Use ``astype`` as an alternative to change the dtype.
  numeric_date = df['Transaction Date'].view('int64')

# ****Drop Rows Which has null values in `Item`, `Price Per Unit` and `Quantity`****

- Dropping these because we are not able to find missing data by just `Total Spent` columns.

In [20]:
df = df.dropna(subset = ['Item', 'Quantity', 'Price Per Unit'], how = 'all')

Find Missing in Price Per Unit using Item column

In [21]:
df['Item'].unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'Sandwich',
       'Juice', 'Tea', nan], dtype=object)

In [22]:
def priceperunit_missing(df):

    maping = {'Coffee' : 2.0, 'Cake' : 3.0, 'Cookie' : 1.0, 'Salad' : 5.0, 'Smoothie' : 4.0, 'Sandwich' : 4.0, 'Tea' : 1.50, 'Juice' : 3.0}

    replace = df['Item'].map(maping)

    df['Price Per Unit'] = df['Price Per Unit'].fillna(replace)

priceperunit_missing(df)
null_calculator(df)

In [23]:
df.isnull().sum()

Transaction ID       0
Item                 3
Quantity            20
Price Per Unit       3
Total Spent         23
Payment Method       0
Location             0
Transaction Date     0
dtype: int64

In [24]:
df[df['Quantity'].isnull()]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
236,TXN_8562645,Salad,NaN,5.0,NaN,Cash,In-store,2023-05-18
278,TXN_3229409,Juice,NaN,3.0,NaN,Cash,Takeaway,2023-04-15
641,TXN_2962976,Juice,NaN,3.0,NaN,Cash,In-store,2023-03-17
738,TXN_8696094,Sandwich,NaN,4.0,NaN,Credit Card,Takeaway,2023-05-14
2796,TXN_9188692,Cake,NaN,3.0,NaN,Credit Card,Takeaway,2023-12-01
3203,TXN_4565754,Smoothie,NaN,4.0,NaN,Digital Wallet,Takeaway,2023-10-06
3224,TXN_6297232,Coffee,NaN,2.0,NaN,Cash,Takeaway,2023-04-07
3401,TXN_3251829,Tea,NaN,1.5,NaN,Digital Wallet,In-store,2023-07-25
4257,TXN_6470865,Coffee,NaN,2.0,NaN,Digital Wallet,Takeaway,2023-09-18
5841,TXN_5884081,Cookie,NaN,1.0,NaN,Digital Wallet,In-store,2023-07-05
7029,TXN_4628338,Coffee,NaN,2.0,NaN,Cash,In-store,2023-12-25
7297,TXN_9944500,Smoothie,NaN,4.0,NaN,Cash,In-store,2023-01-03
8021,TXN_2428781,Salad,NaN,5.0,NaN,Cash,In-store,2023-05-09
8443,TXN_2023651,Sandwich,NaN,4.0,NaN,Cash,In-store,2023-05-25
8465,TXN_9669616,Coffee,NaN,2.0,NaN,Cash,In-store,2023-06-03
8479,TXN_1547245,Sandwich,NaN,4.0,NaN,Digital Wallet,Takeaway,2023-09-11
8574,TXN_2546684,Juice,NaN,3.0,NaN,Digital Wallet,Takeaway,2023-04-08
8732,TXN_4550558,Cookie,NaN,1.0,NaN,Credit Card,In-store,2023-08-04
9590,TXN_9924732,Sandwich,NaN,4.0,NaN,Credit Card,In-store,2023-01-18
9869,TXN_1975184,Coffee,NaN,2.0,NaN,Digital Wallet,In-store,2023-01-15

In [25]:
df[df['Item'].isna()]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
1761,TXN_3611851,NaN,4.0,NaN,NaN,Credit Card,Takeaway,2023-02-09
2289,TXN_7524977,NaN,4.0,NaN,NaN,Digital Wallet,Takeaway,2023-12-09
4152,TXN_9646000,NaN,2.0,NaN,NaN,Digital Wallet,In-store,2023-12-14

In [26]:
df[df['Price Per Unit'].isna()]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
1761,TXN_3611851,NaN,4.0,NaN,NaN,Credit Card,Takeaway,2023-02-09
2289,TXN_7524977,NaN,4.0,NaN,NaN,Digital Wallet,Takeaway,2023-12-09
4152,TXN_9646000,NaN,2.0,NaN,NaN,Digital Wallet,In-store,2023-12-14

In [27]:
df[df['Total Spent'].isna()]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
236,TXN_8562645,Salad,NaN,5.0,NaN,Cash,In-store,2023-05-18
278,TXN_3229409,Juice,NaN,3.0,NaN,Cash,Takeaway,2023-04-15
641,TXN_2962976,Juice,NaN,3.0,NaN,Cash,In-store,2023-03-17
738,TXN_8696094,Sandwich,NaN,4.0,NaN,Credit Card,Takeaway,2023-05-14
1761,TXN_3611851,NaN,4.0,NaN,NaN,Credit Card,Takeaway,2023-02-09
2289,TXN_7524977,NaN,4.0,NaN,NaN,Digital Wallet,Takeaway,2023-12-09
2796,TXN_9188692,Cake,NaN,3.0,NaN,Credit Card,Takeaway,2023-12-01
3203,TXN_4565754,Smoothie,NaN,4.0,NaN,Digital Wallet,Takeaway,2023-10-06
3224,TXN_6297232,Coffee,NaN,2.0,NaN,Cash,Takeaway,2023-04-07
3401,TXN_3251829,Tea,NaN,1.5,NaN,Digital Wallet,In-store,2023-07-25
4152,TXN_9646000,NaN,2.0,NaN,NaN,Digital Wallet,In-store,2023-12-14
4257,TXN_6470865,Coffee,NaN,2.0,NaN,Digital Wallet,Takeaway,2023-09-18
5841,TXN_5884081,Cookie,NaN,1.0,NaN,Digital Wallet,In-store,2023-07-05
7029,TXN_4628338,Coffee,NaN,2.0,NaN,Cash,In-store,2023-12-25
7297,TXN_9944500,Smoothie,NaN,4.0,NaN,Cash,In-store,2023-01-03
8021,TXN_2428781,Salad,NaN,5.0,NaN,Cash,In-store,2023-05-09
8443,TXN_2023651,Sandwich,NaN,4.0,NaN,Cash,In-store,2023-05-25
8465,TXN_9669616,Coffee,NaN,2.0,NaN,Cash,In-store,2023-06-03
8479,TXN_1547245,Sandwich,NaN,4.0,NaN,Digital Wallet,Takeaway,2023-09-11
8574,TXN_2546684,Juice,NaN,3.0,NaN,Digital Wallet,Takeaway,2023-04-08
8732,TXN_4550558,Cookie,NaN,1.0,NaN,Credit Card,In-store,2023-08-04
9590,TXN_9924732,Sandwich,NaN,4.0,NaN,Credit Card,In-store,2023-01-18
9869,TXN_1975184,Coffee,NaN,2.0,NaN,Digital Wallet,In-store,2023-01-15

## ****From above remaining missing data none of values can be calculated so we have to drop all these rows****

In [28]:
df.dropna(inplace = True)
df.isnull().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [29]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,Credit Card,In-store,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-08-30
9996,TXN_9659401,Cookie,3.0,1.0,3.0,Digital Wallet,In-store,2023-06-02
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,Takeaway,2023-03-02
9998,TXN_7695629,Cookie,3.0,1.0,3.0,Digital Wallet,Takeaway,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [30]:
# Calculate loss
rows_lost = raw_data.shape[0] - df.shape[0]
percent_lost = (rows_lost / raw_data.shape[0]) * 100

print(f"\033[1m{' DATA CLEANING SUMMARY ':^50}\033[0m")
print("=" * 50)

print(f"{'Metric':<25} | {'Raw Data':<10} | {'Cleaned':<10}")
print("-" * 50)
print(f"{'Number of Rows':<25} | {raw_data.shape[0]:<10} | {df.shape[0]:<10}")
print(f"{'Number of Columns':<25} | {raw_data.shape[1]:<10} | {df.shape[1]:<10}")

print("-" * 50)
print(f"\033[91m{'Total Rows Removed':<25} : {rows_lost}\033[0m")
print(f"\033[91m{'Data Loss Percentage':<25} : {percent_lost:.2f}%\033[0m")
print("=" * 50)

              DATA CLEANING SUMMARY
==================================================
Metric                    | Raw Data   | Cleaned
--------------------------------------------------
Number of Rows            | 10000      | 9974
Number of Columns         | 8          | 8
--------------------------------------------------
Total Rows Removed        : 26
Data Loss Percentage      : 0.26%
==================================================

In [32]:
df.to_csv('cafe_sales_cleaned.csv', index=False)